### ISSUE TITLE
How to resume an incomplete deletion

### ISSUE THREAD

**Issue by ccharlton** [emcrisostomo/Time-Machine-Cleanup#2]
Love the TM Cleaner script, thank you for posting. Here's my issue...

I had to cancel a deletion of an old backup. I now want to delete that old [incomplete] backup, but `tmutil` won't list or recognize that backup date. What do you suggest?

**Comment by emcrisostomo** [comment]
Thanks @ccharlton, the easiest way is perhaps `rm`-ing the folder from its location into the Time Machine backup.  You can get the Time Machine backup location using `tmutil`:

```
tmutil destinationinfo
```

To make sure it gets mounted, you may execute

```
tmutil listbackups
```

You then use the `URL` property and `mount` info to determine where the backup is mounted onto your machine and remove the corresponding folder (it may be something like this):

```
sudo rm -r /path/to/tm/backup/Backups.backupdb/2016-04-13163825
```
