### ISSUE TITLE
Feature request: schema for backup deletion

### ISSUE THREAD

**Issue by guppie70** [emcrisostomo/Time-Machine-Cleanup#3]
Hi Enrico,

I like this utility a lot!
This is more a feature request than a bug report :-)
Would it be really hard to extend the script with an option to have the backups being removed in a more fine grained way?
Like:
- keep the first (oldest) backup
- keep all the backups for the last 7 days
- keep one backup for each week
- use a maximum of 20 backups
  Think this would be really helpful!
  Regards,

Johan.

**Comment by emcrisostomo** [comment]
Hi @guppie70,

I think they are nice features. I don't have a timeframe for them, however.

Just for your information, at the moment I'm releasing a new version of this script that allows you to keep the latest _n_ backups.
