### ISSUE TITLE
No ./configure script?

### ISSUE THREAD

**Issue by ecjb1969** [emcrisostomo/Time-Machine-Cleanup#9]
I tried running autogen.sh and I have XCode installed, but it doesn't work:

`ecjb@ECJBMBP21 Time-Machine-Cleanup % ./autogen.sh`
`./autogen.sh: line 20: autoreconf: command not found`

**Comment by ecjb1969** [comment]
When doing a git clone, the configure script is missing.  It is only when downloading the release that the configure script is found.

BTW:  how do I download the dialog package?  `brew install dialog` or something similar?

**Comment by ecjb1969** [comment]
`brew install dialog` did indeed install that package.  However, attempting to use it with no parameters led to a hard-to-use menu.  I'm used to the ncurses-style menuing where the arrow keys and tab switch the different buttons.  Using these keys broke the menu, and pressing CTRL+C brought me back to the menu.

When using the `-d days` parameter, I got an error something along the lines of "Unexpected name xxx.backup.  Aborting."  After cleaning up using the `-n num` parameter and repeating `-d days`, the error went away.  I think maybe a better behavior would be to skip directories it doesn't recognize?

**Comment by emcrisostomo** [comment]
Hi,

On your questions:
* Yep, the `configure` script is generated by the build system, and it's not checked in into the repository.
* On the unexpected backup name: quite some time has passed since I wrote this script, so it's likely some behaviour has changed. Do you have an example of the invalid naming?

In the meantime, I'm closing this issue, and feel free to open another one to describe the issue you're facing.

**Comment by ecjb1969** [comment]
I have a feeling that it was a one-off issue.  Perhaps a backup got
interrupted and was resumed later, causing the naming issue.  Like I
mentioned, using the -n num parameter solved the problem.

Also, the dialog-driven script did not behave as expected when using cursor
keys and tab to attempt to navigate the menu.  Weirdly, it seemed to work
better over SSH to my other machine.  I usually use iTerm, so I don't know
if this caused the odd ncurses-style menu issue.

The machine that had the xxx.backup issue also is one that backs up across
the network to the other machine.

*— Eric C. Berlin, MIS.*
ECJB Computer Services, LLC
***@***.***  Skype:  ecjb1969
------------------------------
609-641-3141  <http://voice.google.com/calls?a=nc,%2B16096413141>(Voice)
EASTERN TIME
609-401-9290 (Cell)
609-641-8241  <http://voice.google.com/calls?a=nc,%2B16096418241>(fax)
2528 Tilton Rd, Trlr 97
Egg Harbor Twp, NJ  08234-1649 “If a million people believe in a dumb idea,
it’s still a dumb idea.” — ECJB.
“I am who I say that I am, which is defined by what I believe, which is how
I try to act.” — ECJB.
ecjb.net <http://www.ecjb.net/>

 — Personal site
ecjb.org <http://www.ecjb.org/>

 — Business site
*Google Profile:* This profile links to my various pages.
We use Angie's List to assess whether we're doing a good job keeping valued
customers like you happy.
Please visit AngiesList.com/Review/8064529
<http://angieslist.com/Review/8064529> to grade our quality of work and
customer service.
HomeAdvisor owns Angie's List now, and you can see reviews here:
https://www.homeadvisor.com/rated.ECJBComputerServices.67288824.html.
My Google business page and reviews can be found here:
https://g.page/ecjb-computer-services-llc.
